var Enum = require('enum');

/**
 *
 * @class enumerationController
 * 
 */
export class enumerationController {

    /**
     * Constructor
     
     *
     * @class EnumerationController
     * @constructor
     * 
     */
    public stateEnum = {
        'AE': "Armed Forces Area"
    };

    public templateIdentifier = new Enum({
        'resetPassword': 2,
        'orderRenewedSuccessfully': 3,
        'orderFailed': 4,
        'orderRenewedViaManualPayment': 5,
        'orderPurchaseSuccessfully': 6,
        'orderRefundSuccessfully': 17,
        'shippingAddressConfirmation': 19,
        'growAlert': process.env.NODE_ENV == "development" ? 35 : 21,
        'MeetupInvite': process.env.NODE_ENV == "development" ? 24 : 0,
        'MeetupUpdate': process.env.NODE_ENV == "development" ? 25 : 0,
        'MeetupCancel': process.env.NODE_ENV == "development" ? 26 : 0
    });

    public smsTemplateIdentifier = new Enum({
        'MeetupUpdate': 12,
        'MeetupCancel': 13
    });

    public siteEnum = new Enum({
        'account': 1,
        'curriculum': 2,
        'builder': 3,
        'game': 4,
        'hub': 5,
        'slider': 6,
        'people': 7,
        'affiliate': 8,
        'habit Student': 10,
        'habit Kids': 11,
        'together': process.env.NODE_ENV == "development" ? 15 : 12,
        'kids music': process.env.NODE_ENV == "development" ? 17 : 13,
        'free trial': process.env.NODE_ENV == "development" ? 18 : 15,
        'books': 19,
        'board': 20
    });

    public siteIdEnum = new Enum({
        '1': 'account',
        '2': 'curriculum',
        '3': 'builder',
        '4': 'game',
        '5': 'hub',
        '6': 'slider',
        '7': 'people',
        '8': 'affiliate',
        '9': 'admin',
        '10': 'habit',
        '11': 'habit kids',
        '12': 'together',
        '13': 'kids music',
        '18': 'free trial',
        '19': 'books',
        '20': 'board'
    });

    public emailServerIdEnum = new Enum({
        'aws': 16,
        'gmail': 17,
        'smtp': 18,
    });

    public paymentServiceEnum = new Enum({
        'Stripe': 1
    });

    public thirdPartyActivityType = new Enum({
        "Product": 1,
        "Subscription": 2,
        "Renewed Subscription": 3,
        "Refund": 4,
        "Contact": 5,
        "Create HubSpot Subscription": 6,
        "Cancel HubSpot Subscription": 7,
        "Create Folder": 8,
        "Create File": 9,
        "Get File": 10,
        "Share File": 11,
        "Delete File": 12,
        "Series Mailchimp Template": 13,
        "addCirclePost": 14,
        "addCircleComment": 15,
        "deleteCircleComment": 16,
        "addCircleSpace": 17,
        "addCircleCommunity": 18,
        "addCircleUser": 19,
        "HubspotWorkflowSubscription": 20,
        "ActiveCampaignContact": 21,
        "ActiveCampaignContactList": 22,
        "ActiveCampaignContactTags": 23,
    });

    public WickedReportPaymentStatusEnum = new Enum({
        "1": "APPROVED",
        "2": "FAILED",
        "3": "REFUNDED",
        "4": "PARTIALLY REFUNDED",
    });

    public ApllicationMenuEnum = new Enum({
        "1": "Header",
        "2": "Footer",
        "3": "Side"
    });

    public circleApplication = new Enum({
        "101405": "2",
        "101414": "2",
        "101416": "2",
        "101423": "2",
        "101424": "2",
        "102997": "2",
        "101408": "4",
        "136059": "5",
        "170002": "6"
    });

    public thirdPartyAPIType = new Enum({
        "wicked_report": 1,
        "hubSpot": 2,
        "cloud_storage": 3,
        "circle": 4,
        "mailChimp": 5,
        "activecampaign": 8
    });

    public thirdPartyAPIResponse = new Enum({
        200: "Success",
        204: "Success Create",
        400: "Submission Rejected",
        403: "Portal isn't allowed to post submissions",
        404: "FormGuid isn't found"
    });

    public shipbobDeliveryStatus = new Enum({
        "Picked": 1,
        "Packed": 2,
        "Labeled": 3,
        "InTransit": 4,
        "Delivered": 5,
        "DeliveryException": 6,
        "OutOfStock": 7,
        "UnknownSku": 8,
        "InactiveSku": 9,
        "PaymentDeclined": 10,
        "MissingTarriffInformation": 11,
        "Manual": 12,
        "InvalidAddress": 13,
        "AutoPause": 14,
        "Cancelled": 15,
    });

    public productIdEnum = new Enum({
        "HubAnnual": 38,
        "HubMonthly": 39,
        "SlidrMonthly": 137,
        "SlidrAnnually": 136,
        "BuilderMonthly": 57103,
        "GrowTogetherYearly": 420856,
        "GrowTogetherMonthly": 420855,
        "GrowYourKidsV2Annual": 70585,
        "GrowYourKidsV3Annual": 274161,
        "GrowYourKidsV5Annual": 368806,
        "GrowYourKidsV6Annual": 420822,
        "GrowYourKidsV4Annual": 334590,
        "GrowYourStudentV1Annual": 581,
        "GrowYourStudentV1Annual2": 52823,
        "GrowYourKidsV5Monthly": 410106,
        "GrowYourKidsV6Monthly": 420829,
        "GrowYourKidsV2Quarterly": 75297,
        "GrowYourStudentV2Annual": 52860,
        "GrowYourStudentV3Annual": 119236,
        "GrowYourKidsV5Quarterly": 368802,
        "GrowYourKidsV6Quarterly": 420827,
        "GrowYourKidsV4Quarterly": 337873,
        "GrowYourStudentV5Annual": 368809,
        "GrowYourStudentV6Annual": 420819,
        "GrowYourStudentV4Annual": 334589,
        "GrowYourKidsV3Quarterly": 274158,
        "GrowYourStudentV5Monthly": 420832,
        "GrowYourStudentV6Monthly": 420830,
        "GrowYourStudentV2Quarterly": 55076,
        "GrowYourStudentV1Quarterly": 38852,
        "GrowYourStudentV3Quarterly": 145144,
        "GrowYourStudentV4Quarterly": 337872,
        "GrowYourStudentV6Quarterly": 420828,
        "GrowYourStudentV5Quarterly": 368807,
        "GrowYourKidsMinistryV2Annual": 70589,
        "GrowYourKidsMinistryV2Annual2": 420846,
        "GrowYourKidsMinistryV3Annual": 274159,
        "GrowYourKidsMinistryV3Annual2": 420848,
        "GrowYourStudentMinistryV1Annual": 582,
        "GrowYourKidsMinistryV5Annual": 368804,
        "GrowYourKidsMinistryV5Annual2": 420850,
        "GrowYourKidsMinistryV6Annual": 418357,
        "GrowYourKidsMinistryV4Annual": 334592,
        "GrowYourKidsMinistryV4Annual2": 420849,
        "GrowYourKidsMinistryV2Monthly": 101136,
        "GrowYourKidsMinistryV4Monthly": 334598,
        "GrowYourKidsMinistryV5Monthly": 368803,
        "GrowYourKidsMinistryV6Monthly": 420824,
        "GrowYourKidsMinistryV3Monthly": 274157,
        "GrowYourGroupMinistryV6Annual": 418359,
        "GrowYourGroupMinistryV5Annual": 369636,
        "GrowYourKidsMinistryV2Quarterly": 70588,
        "GrowYourGroupMinistryV5Monthly": 408918,
        "GrowYourStudentMinistryV1Monthly": 2296,
        "GrowYourGroupMinistryV6Monthly": 420826,
        "GrowYourStudentMinistryV2Annual": 52862,
        "GrowYourStudentMinistryV5Annual": 368811,
        "GrowYourStudentMinistryV5Annual2": 420851,
        "GrowYourStudentMinistryV2Monthly": 54493,
        "GrowYourKidsMinistryV5Quarterly": 368805,
        "GrowYourKidsMinistryV6Quarterly": 420821,
        "GrowYourStudentMinistryV3Annual": 119234,
        "GrowYourStudentMinistryV3Annual2": 420847,
        "GrowYourKidsMinistryV4Quarterly": 334591,
        "GrowYourStudentMinistryV4Annual": 334585,
        "GrowYourStudentMinistryV4Annual2": 420844,
        "GrowYourStudentMinistryV6Annual": 418358,
        "GrowYourKidsMinistryV3Quarterly": 274160,
        "GrowYourStudentMinistryV3Monthly": 145142,
        "GrowYourGroupMinistryV6Quarterly": 420823,
        "GrowYourStudentMinistryV6Monthly": 420825,
        "GrowYourStudentMinistryV1Quarterly": 1212,
        "GrowYourStudentMinistryV1Quarterly2": 38859,
        "GrowYourGroupMinistryV5Quarterly": 369637,
        "GrowYourStudentMinistryV4Monthly": 334593,
        "GrowYourStudentMinistryV5Monthly": 368808,
        "GrowYourStudentMinistryV2Quarterly": 52861,
        "GrowYourStudentMinistryV6Quarterly": 420820,
        "GrowYourStudentMinistryV6Quarterly2": 420854,
        "GrowYourStudentMinistryV3Quarterly": 119235,
        "GrowYourStudentMinistryV5Quarterly": 368810,
        "GrowYourStudentMinistryV4Quarterly": 334588,
        "GrowYourStudentV7Quarterly": 420877,
        "GrowYourStudentV7Monthly": 420876,
        "GrowYourStudentV7Annual": 420878,
        "GrowYourStudentBasicV7Quarterly": 420874,
        "GrowYourStudentBasicV7Monthly": 420873,
        "GrowYourStudentBasicV7Annual": 420875,
        "GrowYourKidsV7Quarterly": 420871,
        "GrowYourKidsV7Monthly": 420870,
        "GrowYourKidsV7Annual": 420872,
        "GrowYourKidsBasicV7Quarterly": 420868,
        "GrowYourKidsBasicV7Monthly": 420867,
        "GrowYourKidsBasicV7Annual": 420869,
        "GrowYourStudentV8Quarterly": 420905,
        "GrowYourStudentV8Monthly": 420904,
        "GrowYourStudentV8Annual": 420906,
        "GrowYourStudentBasicV8Quarterly": 420902,
        "GrowYourStudentBasicV8Monthly": 420901,
        "GrowYourStudentBasicV8Annual": 420903,
        "GrowYourKidsV8Quarterly": 420899,
        "GrowYourKidsV8Monthly": 420898,
        "GrowYourKidsV8Annual": 420900,
        "GrowYourKidsBasicV8Quarterly": 420896,
        "GrowYourKidsBasicV8Monthly": 420895,
        "GrowYourKidsBasicV8Annual": 420897,
        "GrowYourKidsV9Annual": 420926,
        "GrowYourKidsV9Monthly": 420924,
        "GrowYourKidsV9Quarterly": 420925,
        "GrowYourStudentV9Annual": 420932,
        "GrowYourStudentV9Monthly": 420930,
        "GrowYourKidsBasicV9Annual": 420923,
        "GrowYourStudentV9Quarterly": 420931,
        "GrowYourKidsBasicV9Monthly": 420921,
        "GrowYourKidsBasicV9Quarterly": 420922,
        "GrowYourStudentBasicV9Annual": 420929,
        "GrowYourStudentBasicV9Monthly": 420927,
        "GrowYourStudentBasicV9Quarterly": 420928,
    });

    public activecampaignList = new Enum({
        "master-contact-list": 1,
        "grow-kids-free-trial-sign-up": 2,
        "grow-students-free-trial-sign-up": 3,
        "v6-all-active-subscribers": 4,
        "hubs-users": 5,
        "slidr-users": 6,
        "v6-gyk-subscribers": 7,
        "v6-gykm-subscribers": 8,
        "v6-gys-subscribers": 9,
        "v6-gym-subscribers": 10,
        "v6-gg-subscribers": 11,
        "sycu-church-leaders": 28,
        // "grow-groups-free-trial-sign-up": 26,
    });

    public activecampaignListTitle = new Enum({
        "master-contact-list": "Master Contact List",
        "grow-kids-free-trial-sign-up": "Grow Kids - Free Trial Sign Up",
        "grow-students-free-trial-sign-up": "Grow Students - Free Trial Sign Up",
        "v6-all-active-subscribers": "V6 All Active Subscribers",
        "hubs-users": "Hubs Users",
        "slidr-users": "Slidr Users",
        "v6-gyk-subscribers": "V6 GYK Subscribers",
        "v6-gykm-subscribers": "V6 GYKM Subscribers",
        "v6-gys-subscribers": "V6-GYS Subscribers",
        "v6-gym-subscribers": "V6-GYM Subscribers",
        "v6-gg-subscribers": "V6 GG Subscribers",
        "sycu-church-leaders": "SYCU Church Leaders",
        // "grow-groups-free-trial-sign-up": "Grow Groups - Free Trial Sign Up",
    });

    public activecampaignTags = new Enum({
        "active-customer-grow-together": 18,
        "active-customer-grow-kids": 12,
        "active-customer-grow-hubs": 16,
        "active-customer-grow-groups": 14,
        "active-customer-grow-slides": 15,
        "active-customer-grow-people": 19,
        "active-customer-grow-students": 13,
        "active-customer-grow-creative-board": 17,
        "active-customer-grow-lesson-builder": 20,
        "former-customer-grow-creative-board": 84,
        "former-customer-grow-lesson-builder": 82,
        "former-customer-grow-students": 86,
        "former-customer-grow-slides": 85,
        "former-customer-grow-people": 83,
        "former-customer-grow-groups": 79,
        "former-customer-grow-kids": 81,
        "former-customer-grow-hubs": 80,
        "former-customer-grow-together": 87,
        "v1-gys": 32,
        "v1-gysm": 33,
        "v2-gyk": 34,
        "v2-gykm": 35,
        "v2-gys": 36,
        "v2-gysm": 37,
        "v3-gyk": 38,
        "v3-gykm": 39,
        "v3-gys": 40,
        "v3-gysm": 41,
        "v4-gyk": 42,
        "v4-gykm": 43,
        "v4-gys": 44,
        "v4-gysm": 45,
        "v5-gyk": 46,
        "v5-gykm": 47,
        "v5-gys": 48,
        "v5-gysm": 49,
        "v5-gg": 107,
        "v6-gyk": 50,
        "v6-gykm": 51,
        "v6-gys": 52,
        "v6-gysm": 53,
        "v6-gg": 108,
        "v7-gyk": 54,
        "v7-gykm": 55,
        "v7-gys": 56,
        "v7-gysm": 57,
        "v8-gyk": 3451,
        "v8-gykm": 3450,
        "v8-gys": 3453,
        "v8-gysm": 3452,
        "v9-gyk": 3531,
        "v9-gykm": 3532,
        "v9-gys": 3530,
        "v9-gysm": 3533,
        "prospect-grow-together": 109,
        "prospect-grow-kids": 60,
        "prospect-grow-hubs": 59,
        "prospect-curriculum": 93,
        "prospect-grow-groups": 58,
        "prospect-grow-slides": 64,
        "prospect-grow-people": 62,
        "prospect-grow-students": 65,
        "prospect-grow-lesson-builder": 61,
        "prospect-grow-creative-board": 63,
        "ministry-role-youth-ministry": 68,
        "ministry-role-kids-ministry": 67,
        "ministry-role-oversee-both": 69,
        "ministry-role-none": 70,
        "vbs-wild-life": 97,
        "vbs-set-sail": 3414,
        "vbs-deep-sea": 95,
        "vbs-i-wonder": 94,
        "vbs-on-the-case": 96,
        "app-grow-tv": 77,
        "app-grow-games": 71,
        "app-grow-hubs": 112,
        "app-grow-habits": 72,
        "app-grow-people": 114,
        "app-grow-curriculum": 78,
        "app-grow-habits-kids": 73,
        "customer-grow-kids-music": 89,
        "failed-payment-grow-together": 106,
        "failed-payment-grow-hubs": 100,
        "failed-payment-grow-kids": 101,
        "failed-payment-grow-groups": 99,
        "failed-payment-grow-people": 103,
        "failed-payment-grow-slides": 104,
        "failed-payment-grow-students": 105,
        "failed-payment-grow-lesson-builder": 102,
        "cart-viewed": 3245,
        "checkout-initiated": 3246,
        "pending-cancellation-hubs": 3512,
        "pending-cancellation-kids": 3302,
        "pending-cancellation-groups": 3510,
        "pending-cancellation-slides": 3513,
        "pending-cancellation-people": 3516,
        "pending-cancellation-students": 3303,
        "pending-cancellation-grow-together": 3518,
        "pending-cancellation-lesson-builder": 3511,
        "pending-cancellation-creative-board": 3514,
        "student-ministry-app-grow-game": 3313,
        "kids-ministry-app-grow-game": 3314,
        "family-ministry-app-grow-game": 3315,
        "non-app-grow-game": 3316,
        "app-grow-kids-music-free-trial": 3354,
        "Prospect-GrowCon24": 3400,
        "Cruise-Giveaway-23": 3401,
        "GrowCon24-Resources-Download": 3410,
        "free-trial-curriculum": 3434,
        "partner-umc-texas": 3441,
        "partner-tbc": 3454,
        "partner-chogy": 3482,
        "partner-umcmo": 3483,
        "partner-umcigr": 3492,
        "shared-access-kids": 3473,
        "shared-access-hubs": 3523,
        "shared-access-board": 3525,
        "shared-access-slides": 3524,
        "shared-access-builder": 3522,
        "shared-access-students": 3474,
        "expired-shared-access-kids": 3475,
        "expired-shared-access-hubs": 3527,
        "expired-shared-access-board": 3529,
        "expired-shared-access-slides": 3528,
        "expired-shared-access-builder": 3526,
        "expired-shared-access-students": 3476,
        "cancelled-curriculum-dissatisfied": 3488,
        "cancelled-curriculum-budget": 3486,
        "cancelled-curriculum-other": 3489,
        "cancelled-curriculum-switch": 3487,
        "cancelled-curriculum-role": 3493,
        "inactive-customer-hubs": 3505,
        "inactive-customer-kids": 3501,
        "inactive-customer-groups": 3503,
        "inactive-customer-slides": 3506,
        "inactive-customer-people": 3509,
        "inactive-customer-numbers": 3508,
        "inactive-customer-students": 3502,
        "inactive-customer-grow-together": 3517,
        "inactive-customer-lesson-builder": 3504,
        "inactive-customer-creative-board": 3507,
    });

    public activecampaignTagsTitle = new Enum({
        "active-customer-grow-together": "Active Customer - Grow Together",
        "active-customer-grow-hubs": "Active Customer - Grow Hubs",
        "active-customer-grow-kids": "Active Customer - Grow Kids",
        "active-customer-grow-groups": "Active Customer - Grow Groups",
        "active-customer-grow-slides": "Active Customer - Grow Slides",
        "active-customer-grow-people": "Active Customer - Grow People",
        "active-customer-grow-students": "Active Customer - Grow Students",
        "active-customer-grow-creative-board": "Active Customer - Grow Creative Board",
        "active-customer-grow-lesson-builder": "Active Customer - Grow Lesson Builder",
        "former-customer-grow-creative-board": "Former Customer - Grow Creative Board",
        "former-customer-grow-lesson-builder": "Former Customer - Grow Lesson Builder",
        "former-customer-grow-students": "Former Customer - Grow Students",
        "former-customer-grow-groups": "Former Customer - Grow Groups",
        "former-customer-grow-slides": "Former Customer - Grow Slides",
        "former-customer-grow-people": "Former Customer - Grow People",
        "former-customer-grow-hubs": "Former Customer - Grow Hubs",
        "former-customer-grow-kids": "Former Customer - Grow Kids",
        "former-customer-grow-together": "Former Customer - Grow Together",
        "v1-gys": "V1 GYS",
        "v1-gysm": "V1 GYSM",
        "v2-gyk": "V2 GYK",
        "v2-gys": "V2 GYS",
        "v2-gykm": "V2 GYKM",
        "v2-gysm": "V2 GYSM",
        "v3-gyk": "V3 GYK",
        "v3-gys": "V3 GYS",
        "v3-gykm": "V3 GYKM",
        "v3-gysm": "V3 GYSM",
        "v4-gyk": "V4 GYK",
        "v4-gys": "V4 GYS",
        "v4-gykm": "V4 GYKM",
        "v4-gysm": "V4 GYSM",
        "v5-gg": "V5 GG",
        "v5-gyk": "V5 GYK",
        "v5-gys": "V5 GYS",
        "v5-gykm": "V5 GYKM",
        "v5-gysm": "V5 GYSM",
        "v6-gg": "V6 GG",
        "v6-gyk": "V6 GYK",
        "v6-gys": "V6 GYS",
        "v6-gykm": "V6 GYKM",
        "v6-gysm": "V6 GYSM",
        "v7-gys": "V7 GYS",
        "v7-gyk": "V7 GYK",
        "v7-gykm": "V7 GYKM",
        "v7-gysm": "V7 GYSM",
        "v8-gys": "V8 GSB",
        "v8-gyk": "V8 GKB",
        "v8-gykm": "V8 GK",
        "v8-gysm": "V8 GS",
        "v9-gys": "V9 GSB",
        "v9-gyk": "V9 GKB",
        "v9-gykm": "V9 GK",
        "v9-gysm": "V9 GS",
        "prospect-grow-hubs": "Prospect - Grow Hubs",
        "prospect-grow-kids": "Prospect - Grow Kids",
        "prospect-curriculum": "Prospect - Curriculum",
        "prospect-grow-groups": "Prospect - Grow Groups",
        "prospect-grow-people": "Prospect - Grow People",
        "prospect-grow-slides": "Prospect - Grow Slides",
        "prospect-grow-students": "Prospect - Grow Students",
        "prospect-grow-together": "Prospect - Grow Together",
        "prospect-grow-lesson-builder": "Prospect - Grow Lesson Builder",
        "prospect-grow-creative-board": "Prospect - Grow Creative Board",
        "ministry-role-youth-ministry": "Ministry Role - Youth Ministry",
        "ministry-role-kids-ministry": "Ministry Role - Kids Ministry",
        "ministry-role-oversee-both": "Ministry Role - Family Ministry",
        "ministry-role-none": "Ministry Role - None",
        "vbs-set-sail": "VBS - Set Sail",
        "vbs-wild-life": "VBS - Wild Life",
        "vbs-deep-sea": "VBS - Deep Sea",
        "vbs-i-wonder": "VBS - I Wonder",
        "vbs-on-the-case": "VBS - On The Case",
        "app-grow-hubs": "App - Hubs",
        "app-grow-tv": "App - Grow TV",
        "app-grow-games": "App - Grow Games",
        "app-grow-people": "App - Grow People",
        "app-grow-habits": "App - Grow Habits",
        "app-grow-curriculum": "App - Grow Curriculum",
        "app-grow-habits-kids": "App - Grow Habits Kids",
        "customer-grow-kids-music": "Customer - Grow Kids Music",
        "failed-payment-grow-together": "Failed Payment - Grow Together",
        "failed-payment-grow-hubs": "Failed Payment - Grow Hubs",
        "failed-payment-grow-kids": "Failed Payment - Grow Kids",
        "failed-payment-grow-groups": "Failed Payment - Grow Groups",
        "failed-payment-grow-slides": "Failed Payment - Grow Slides",
        "failed-payment-grow-people": "Failed Payment - Grow People",
        "failed-payment-grow-students": "Failed Payment - Grow Students",
        "failed-payment-grow-lesson-builder": "Failed Payment - Grow Lesson Builder",
        "pending-cancellation-hubs": "Pending Cancellation - Hubs",
        "pending-cancellation-kids": "Pending Cancellation - Kids",
        "pending-cancellation-groups": "Pending Cancellation - Groups",
        "pending-cancellation-slides": "Pending Cancellation - Slides",
        "pending-cancellation-people": "Pending Cancellation - People",
        "pending-cancellation-students": "Pending Cancellation - Students",
        "pending-cancellation-grow-together": "Pending Cancellation - Grow Together",
        "pending-cancellation-lesson-builder": "Pending Cancellation - Lesson Builder",
        "pending-cancellation-creative-board": "Pending Cancellation - Creative Board",
        "student-ministry-app-grow-game": "Student Ministry App-Grow Game",
        "kids-ministry-app-grow-game": "Kids Ministry App-Grow Game",
        "family-ministry-app-grow-game": "Family Ministry App-Grow Game",
        "non-app-grow-game": "Non App-Grow Game",
        "app-grow-kids-music-free-trial": "App - Grow Kids Music Free Trial",
        "Prospect-GrowCon24": "Prospect - GrowCon24",
        "Cruise-Giveaway-23": "Cruise Giveaway 23",
        "GrowCon24-Resources-Download": "GrowCon24 Resources Download",
        "free-trial-curriculum": "Free Trial - Curriculum",
        "partner-umc-texas": "Partner - UMC Texas",
        "partner-tbc": "Partner - The Brethren Church",
        "partner-chogy": "Partner - Church of God Ministries",
        "partner-umcmo": "Partner - UMC Missouri",
        "partner-umcigr": "Partner - UMC IGR",
        "shared-access-kids": "Shared Access - Kids",
        "shared-access-hubs": "Shared Access - Hubs",
        "shared-access-slides": "Shared Access - Slides",
        "shared-access-students": "Shared Access - Students",
        "shared-access-board": "Shared Access - Creative Board",
        "shared-access-builder": "Shared Access - Lesson Builder",
        "expired-shared-access-kids": "Expired Shared Access - Kids",
        "expired-shared-access-hubs": "Expired Shared Access - Hubs",
        "expired-shared-access-slides": "Expired Shared Access - Slides",
        "expired-shared-access-students": "Expired Shared Access - Students",
        "expired-shared-access-board": "Expired Shared Access - Creative Board",
        "expired-shared-access-builder": "Expired Shared Access - Lesson Builder",
        "cancelled-curriculum-role": "Cancelled Curriculum - Role",
        "cancelled-curriculum-other": "Cancelled Curriculum - Other",
        "cancelled-curriculum-budget": "Cancelled Curriculum - Budget",
        "cancelled-curriculum-switch": "Cancelled Curriculum - Switch",
        "cancelled-curriculum-dissatisfied": "Cancelled Curriculum - Dissatisfied",
        "inactive-customer-hubs": "Inactive Customer - Hubs",
        "inactive-customer-kids": "Inactive Customer - Kids",
        "inactive-customer-groups": "Inactive Customer - Groups",
        "inactive-customer-slides": "Inactive Customer - Slides",
        "inactive-customer-people": "Inactive Customer - People",
        "inactive-customer-numbers": "Inactive Customer - Numbers",
        "inactive-customer-students": "Inactive Customer - Students",
        "inactive-customer-grow-together": "Inactive Customer - Grow Together",
        "inactive-customer-lesson-builder": "Inactive Customer - Lesson Builder",
        "inactive-customer-creative-board": "Inactive Customer - Creative Board",
    });

    public geoConfigData = new Enum({
        "kids": 1,
        "student": 2,
        "groups": 3,
        "hub": 4,
        "slider": 5,
        "people": 6,
        "builder": 7,
        "Together": 8
    });

    public siteUrlEnum = new Enum({
        'https://accounts.stuffyoucanuse.dev/': 1,
        'https://curriculum.stuffyoucanuse.dev/': 2,
        'https://builder.stuffyoucanuse.dev/': 3,
        'https://games.stuffyoucanuse.dev/': 4,
        'https://hubs.stuffyoucanuse.dev/': 5,
        'https://slidr.stuffyoucanuse.dev/': 6,
        'https://people.stuffyoucanuse.dev/': 7,
        'https://affiliate.stuffyoucanuse.dev/': 8,
        'https://admin.stuffyoucanuse.dev/': 9,
        'https://growyou.stuffyoucanuse.dev/': 12,
    });

    public volumePageIdEnum = new Enum({
        1: 65,
        2: 66,
        3: 52,
        4: 63,
        5: 64,
        8: 55,
        9: 66,
        10: 53,
        11: 54,
        12: 56,
        13: 57,
        14: 58,
        15: 59,
        16: 60,
        17: 61,
        20: 52,
        21: 53,
        26: 49,
        27: 49,
        28: 50,
        29: 50,
        31: 55,
        32: 56,
        33: 57,
        34: 58,
        35: 59,
        36: 60,
        37: 61,
        38: 51
    });

    public categoryIDEnum = new Enum({
        "musicCategoryId": process.env.NODE_ENV == "development" ? 183 : 188,
        // "vbsCategoryPageId": process.env.NODE_ENV == "development" ? 32 : 62,
    });

    public membershipStatus = new Enum({
        1: "Pending",
        2: "Active",
        3: "On Hold",
        4: "Pending Cancellation",
        5: "Cancelled",
        6: "Expired",
        7: "Failed",
        8: "Completed",
        9: "Check Pending",
        10: "Pending Cancellation",
        11: "Paused",
        12: "Refund"
    });
}
